name: Weekly Termonaut Report

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  weekly-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Termonaut
      run: |
        go install github.com/oiahoon/termonaut-profile/cmd/termonaut@latest

    - name: Generate Weekly Report
      run: |
        mkdir -p reports

        if [ -f ".termonaut/termonaut.db" ]; then
          # Generate weekly report
          WEEK=$(date +'%Y-W%U')
          termonaut analytics weekly --output=reports/week-$WEEK.md

          # Update latest report
          cp reports/week-$WEEK.md reports/latest-weekly.md
        fi

    - name: Create Issue with Report
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          try {
            const report = fs.readFileSync('reports/latest-weekly.md', 'utf8');

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '📊 Weekly Termonaut Report - Week ' + new Date().toISOString().slice(0, 10),
              body: report,
              labels: ['termonaut', 'weekly-report']
            });
          } catch (error) {
            console.log('No report generated or error creating issue:', error);
          }

    - name: Commit reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/ || true
        git diff --staged --quiet || git commit -m "📈 Weekly Termonaut report - $(date +'%Y-W%U')"
        git push
